server:
  port: 8083
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.0.13:8848
  application:
    name: service-passerger-user
  redis:
    port: 6379
    host: localhost
    database: 0
